# Generated by Django 5.0 on 2026-02-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.AddField(
            model_name='profile',
            name='summary',
            field=models.TextField(blank=True, help_text='Short professional summary'),
        ),
    ]
