# Generated by Django 5.0 on 2026-02-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CONSULTANT', 'Consultant'), ('JOBSEEKER', 'Job Seeker')], default='JOBSEEKER', max_length=20),
        ),
    ]
