# Generated by Django 5.0 on 2026-02-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='applied_on',
            new_name='applied_at',
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], default='applied', max_length=20),
        ),
    ]
