# Generated by Django 5.0 on 2026-02-10 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('TECHNICAL', 'Technical'), ('BEHAVIORAL', 'Behavioral'), ('CASE', 'Case Study')], max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('feedback_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultants.consultant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
