# Generated by Django 5.0 on 2026-02-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_interviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mockinterview',
            name='feedback_uploaded_at',
        ),
        migrations.AddField(
            model_name='mockinterview',
            name='feedback_report',
            field=models.FileField(blank=True, null=True, upload_to='mock_interviews/'),
        ),
        migrations.AlterField(
            model_name='mockinterview',
            name='interview_type',
            field=models.CharField(choices=[('TECH', 'Technical'), ('HR', 'Behavioral'), ('CASE', 'Case Study')], max_length=10),
        ),
    ]
