# Generated by Django 5.0 on 2026-02-10 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_interviews', '0002_remove_mockinterview_feedback_uploaded_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mockinterview',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='mockinterview',
            name='feedback_report',
        ),
        migrations.AddField(
            model_name='mockinterview',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mockinterview',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mockinterview',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20),
        ),
        migrations.AlterField(
            model_name='mockinterview',
            name='consultant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_interviews_taken', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mockinterview',
            name='interview_type',
            field=models.CharField(choices=[('TECH', 'Technical'), ('BEHAV', 'Behavioral'), ('CASE', 'Case Study')], max_length=10),
        ),
    ]
