# Generated by Django 5.0 on 2026-02-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_interviews', '0003_remove_mockinterview_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockinterview',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
