# Generated by Django 5.0 on 2026-02-14 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_interviews', '0004_mockinterview_completed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mockinterview',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mockinterview',
            name='consultant',
            field=models.ForeignKey(blank=True, limit_choices_to={'userprofile__role': 'CONSULTANT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_interviews_taken', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mockinterview',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20),
        ),
    ]
