# Generated by Django 5.0 on 2026-02-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_interviews', '0005_mockinterview_meeting_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockinterview',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
