# Generated by Django 5.0 on 2026-02-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultant',
            name='is_dedicated',
        ),
        migrations.RemoveField(
            model_name='consultantsession',
            name='meeting_link',
        ),
        migrations.RemoveField(
            model_name='consultantsession',
            name='session_type',
        ),
        migrations.RemoveField(
            model_name='consultantsession',
            name='sla_deadline',
        ),
        migrations.AddField(
            model_name='consultantsession',
            name='plan',
            field=models.CharField(choices=[('PRO', 'Pro'), ('PRO_PLUS', 'Pro Plus')], default='FREE', max_length=20),
        ),
        migrations.AddField(
            model_name='consultantsession',
            name='sla_hours',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='expertise',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='consultantsession',
            name='duration_minutes',
            field=models.IntegerField(default=30),
        ),
    ]
