# Generated by Django 5.0 on 2026-02-10 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0002_remove_consultant_is_dedicated_and_more'),
        ('session_notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionnote',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionnote',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='sessionnote',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consultants.consultantsession'),
        ),
        migrations.DeleteModel(
            name='SessionFeedback',
        ),
    ]
