# Generated by Django 5.0 on 2026-02-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_rename_active_subscription_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='consultant_sessions_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='mock_interviews_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='resume_reviews_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
