# Generated by Django 5.0 on 2026-02-10 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='original_file',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume_score',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='reviewed_by',
        ),
        migrations.AddField(
            model_name='resume',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='optimized_file',
            field=models.FileField(blank=True, null=True, upload_to='optimized_resumes/'),
        ),
        migrations.CreateModel(
            name='ResumeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('PRO', 'Pro'), ('PRO_PLUS', 'Pro Plus')], max_length=10)),
                ('suggestions', models.TextField()),
                ('score', models.IntegerField(default=0)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
    ]
