# Generated by Django 5.0 on 2026-02-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='certificate_generated',
            field=models.BooleanField(default=False),
        ),
    ]
