# Generated by Django 5.0 on 2026-02-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_courseenrollment_certificate_generated'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='courseenrollment',
            name='completed_on',
        ),
    ]
